### ISSUE TITLE
Inrichten testomgeving

### ISSUE THREAD

**Issue by martineteirlinck** [nppo/search-portal#15]

**Comment by fako** [comment]
Er moet een AWS omgeving aangemaakt worden door een SURF medewerker. Is het duidelijk dat maandelijkse kosten hiermee gaan verdubbelen? Moet de uiteindelijke beheerder deze taak niet op zich nemen i.p.v. het project team? Normaal gesproken zijn er 3 verschillende omgevingen, dev, acc en prod. Gaan we alle drie doen?

**Comment by fako** [comment]
Account voor acc is aangemaakt.

**Comment by fako** [comment]
Openstaande taken:
- [x] Data migratie voor sources.acc.publinova.nl
