### ISSUE TITLE
Koppeling HKU search

### ISSUE THREAD

**Issue by martineteirlinck** [nppo/search-portal#17]
Koppeling op eigen repository:

**Comment by fako** [comment]
Fako moet mail schrijven over naam velden en wensen rondom API

**Comment by fako** [comment]
Links ontvangen per email klaar om mee te beginnen.

**Comment by fako** [comment]
Weer een lijstje met mogelijke problemen:
- [x] Copyright is nergens beschikbaar. Wat maken we de default?
- [x] Mime type ontbreekt. Even kijken of Emile die nog kan aanleveren
- [x] Keywords zijn een chaos. Even kijken of Emile daarin iets kan betekenen
- [x] Authors zijn niet direct koppelbaar aan personen. Kijken of Emile daarin iets kan betekenen
- [x] Themes en object type ontbreken. Kunnen we extra vragen aan Emile, maar moeten deze velden niet gewoon weg?

**Comment by JohnMeurs** [comment]
@martineteirlinck  Contact opnemen Emile. Die bepaalt de default, die forceert de Copyrights.
Overige punten van commentaar boven: Zijn **niet** blokkerend.

**Comment by JohnMeurs** [comment]
@martineteirlinck Themes en Objects hoe doet hBO kennisbank. Dan besluit nemen

**Comment by fako** [comment]
Emile heeft antwoord gegeven. Kan ik spoedig oppakken.

**Comment by fako** [comment]
Verder afgehandeld:
- Copyright wordt nu cc-by-nc-40.
- Mimetype ontbreekt nog steeds soms, maar we vullen in wat we kunnen op basis van Emile's feedback
- Keywords blijven onbetrouwbaar, maar we doen wat we kunnen
- Person ids extraheren we nu zoveel mogelijk

Mogelijk willen we graag dat HKU onze licentie encodings gebruikt? Dan kan ik dat nog doorgeven aan Emile. Vast een kleine wijziging.

Wacht nu alleen op besluit over themes en object types door @martineteirlinck. Licentie is dus afgetikt (had Emile al op geantwoord).

**Comment by fako** [comment]
Closing. Theme and object type problems will be resolved with: https://github.com/nppo/search-portal/issues/50

**Comment by fako** [comment]
Needs testing. Close when that's done

**Comment by fako** [comment]
Volgens “gentlemans agreement”
