### ISSUE TITLE
Zoeken in personen?

### ISSUE THREAD

**Issue by martineteirlinck** [nppo/search-portal#23]
Als een bronsysteen als Pure personen en projecten aanlevert, is het dan ingewikkeld/ veel werk om daar jouw zoekmachine voor te gebruiken? Er zijn geen documenten om te doorzoeken.

**Comment by fako** [comment]
Dit wordt nu opgelost door Zooma. Welk probleem is er met Zooma waarvan je verwacht dat het opgelost wordt als Datascope Search het gaat oplossen? Het is nu niet duidelijk wat het beoogde resultaat is en hoeveel werk dat dan zou zijn.

**Comment by fako** [comment]
Zoeken in personen en projecten gaat niet perse makkelijk via PPP. Omdat de PPP requests doet naar de bron en niets opslaat. Opslag wordt geregeld door Main en regelt ook het zoeken.
