### ISSUE TITLE
Koppeling VHL search

### ISSUE THREAD

**Issue by martineteirlinck** [nppo/search-portal#25]
Greeni

**Comment by fako** [comment]
Fako wacht op link van Marijke en Richard

**Comment by fako** [comment]
Dit is de link: https://www.greeni.nl/webopac/oai2.CSP?verb=ListRecords&metadataPrefix=didl&set=PUBVHL

Andere sets: PUBHAS en PUBAERES

**Comment by fako** [comment]
Deletes komen niet door

**Comment by fako** [comment]
Copyright is gespecificeerd per file. Het gaat daarbij om open vs. closed i.p.v. de licentie. Kunnen we een default copyright afspreken en wanneer is een product open? Als alle files "open" zijn? Als de eerste file "open" is?

**Comment by fako** [comment]
Publisher wordt nu weer uit het publisher veld gepakt. Misschien toch nog even goed kijken naar "consortium" voor NPPO. Zit er nu niet in, maar is wellicht de betere oplossing.

**Comment by fako** [comment]
Publisher date zou ik er toch uitgooien. Dat we modified daar opslaan lijkt mij verwarrend.

**Comment by JohnMeurs** [comment]
@martineteirlinck Volgende acties:
Copyright defeties opvragen (wat is open , wat is closed) en dan mappen op ons lijstje van mogelijkheden. Wel wijzen op de gevolgen (niet doorzoekbaar bv).

@martineteirlinck @JohnMeurs voorstel maken voor publisher,consortium problematiek, dit afstemmen met @fako  en dan ticket voor ontwikkeling.

@JohnMeurs Eva gevolg van nu niks doen: erg veel partij onbekend uitleggen en mogelijk herzien

**Comment by fako** [comment]
Publisher date wordt nu niet ingevuld. Verder blijven er open vragen

**Comment by fako** [comment]
Ik heb de ticket vast aangemaakt voor standardization van publisher, consortia, etc.: https://github.com/nppo/search-portal/issues/51

Verder wacht deze ticket alleen nog op copyright indicatie vanuit instelling.

**Comment by martineteirlinck** [comment]
@fako wat is de status? Nog iets van ons nodig hierin en wanneer verwacht je hem af te kunnen ronden?

**Comment by fako** [comment]
Volgens “gentlemans agreement”
