### ISSUE TITLE
Koppeling HAN/Metis search

### ISSUE THREAD

**Issue by martineteirlinck** [nppo/search-portal#26]
Er zijn een paar mogelijke problemen met deze koppeling:
- [x] De copyright is ofwel "open" ofwel "closed". Hierdoor is onduidelijk welke copyright geldt. Hierdoor kunnen we geen full text search uitvoeren
- [x] Het grootste deel van de producten heeft een closed access policy. Ongeveer 1/3 is open (op basis van eerste 200 producten)
- [x] Taal is niet beschikbaar. Hierdoor zal het zoeken suboptimaal werken
- [x] Keywords zijn niet aanwezig lijkt het. Dat is niet helemaal zoals verwacht.
- [x] Files hebben geen titles, dit is mogelijk geen probleem, hangt af van hoe Main dit afhandeld.
- [x] Namen zijn in de vorm van: "\<achternaam\>, \<voornaam\>"
- [x] Publisher_date wordt modified_at en we gebruiken wel publisher_year. Wat zijn de wensen?
- [x] Wat gaan we doen met mods:genre? Is dat research_object_type?
- [x] Research themes doen we momenteel niets mee. Wat willen we?

**Comment by fako** [comment]
Fako wacht op URL van Michel en Hans

**Comment by fako** [comment]
Michel heeft gereageerd. Klaar voor implementatie

**Comment by martineteirlinck** [comment]
Fijn Fako! kun jij zo aan de gang of ben je dat al?

**Comment by fako** [comment]
Vandaag begonnen. Morgen nog een paar uur, maar verder veel contract dingen en meetings deze week.

**Comment by fako** [comment]
Namen moeten als "voornaam achternaam"
File titles moeten bestandsnaam worden
Publisher moet HAN worden

Vragen naar: keywords en taal. Kan dit nog naar buiten komen?

**Comment by fako** [comment]
Als we een klap kunnen geven op de copyright, dan kan ik daarna dit op prod aanzetten om te kijken wat er gebeurd @martineteirlinck

**Comment by JohnMeurs** [comment]
@martineteirlinck SCHIET op!!!

**Comment by fako** [comment]
Volgens “gentlemans agreement”

**Comment by fako** [comment]
Copyright kan "open-access" zijn en dan passen we full text search toe.
