### ISSUE TITLE
Koppeling BUAS search

### ISSUE THREAD

**Issue by martineteirlinck** [nppo/search-portal#34]
Pure

Lijkt sterk op de Pure v2 API, maar BUAS gebruikt Pure v1.

**Comment by fako** [comment]
Dingen die zijn opgevallen:
- [x] Weer alleen Engels als taal
- [x] Geen description
- [x] Geen e-mail
- [x] Geen DOI
- [ ] Geen enkel materiaal voldoet aan copyright eisen
- [x] Geen keywords

**Comment by fako** [comment]
Hoe moeten we omgaan met test data?

**Comment by fako** [comment]
Suggestie van Jan was om organizational units te gebruiken voor email adressen. Daarmee zouden we bijvoorbeeld een email adres kunnen krijgen, die dan hoort bij de organisatie "Placemaking and Events". Dit is niet helemaal het niveau waarop we de email adressen willen verkrijgen, dus ik laat het voorlopig zitten @JohnMeurs

**Comment by fako** [comment]
Over de gebruik licenties heb ik nu een email aan @martineteirlinck gestuurd. Ga er vooralsnog vanuit dat licentie "open-access" wordt, zoals we met andere instellingen ook doen. Misschien dat BUAS toch andere afspraken wilt maken, maar dat hoor ik dan wel.

**Comment by fako** [comment]
Volgens “gentlemans agreement”
