### ISSUE TITLE
Koppeling HvA search

### ISSUE THREAD

**Issue by martineteirlinck** [nppo/search-portal#36]
Pure

**Comment by fako** [comment]
Ze gaan kijken of ze via Elsevier de nieuwe PURE API kunnen gaan gebruiken, waar ze meer controle hebben over de data. Eventueel is er een OAI-PMH fallback. Er is ook een oude API, maar die is misschien niet AVG geschikt. Voorkeur ligt bij de nieuwe API waar we volgende week meer over horen.

**Comment by fako** [comment]
Hier weer even een lijst met aandachtspunten na de eerste versie van de koppeling:
- [x] Copyright is open/closed waardoor we geen CC weten waardoor full text niet mag
- [x] Er zijn relatief weinig bestanden is mijn eerste indruk
- [x] Open access is ongeveer 1/3 lijkt het (op basis van eerste 20)
- [x] Publisher_date is weer de modified date geworden. Misschien moeten we dit veld laten vallen?
- [x] Themes lijken niet beschikbaar 
- [x] research_object_type gemapt vanaf type
- [x] DOI is er op file niveau
- [x] Alles lijkt gelabeld met en_GB, ook Nederlandse teksten

**Comment by JohnMeurs** [comment]
Besluit: publicatie datum leeg, blijft

**Comment by JohnMeurs** [comment]
@martineteirlinck Opvragen bij HBO kennisbank. Anders leeg.

**Comment by JohnMeurs** [comment]
@fako wij maken een mapper. @martine maakt voorstel aan onze zijde en stemt af welke types per instelling naar welk Publinova type gaan.

**Comment by JohnMeurs** [comment]
@fako  DOI, pak de eerste.

**Comment by fako** [comment]
DOI wordt nu verwerkt. Alleen nog wachten op copyright

**Comment by fako** [comment]
Wachtend op productie credentials

**Comment by fako** [comment]
Productie credentials opgenomen in AWS. Zal met volgende release beschikbaar komen, maar eerst testen en tonen op acceptatie omgevingen.

**Comment by fako** [comment]
Volgens “gentlemans agreement”
