### ISSUE TITLE
Integratie met Edusources

### ISSUE THREAD

**Issue by fako** [nppo/search-portal#56]
Voordelen die ik zie:
    * Scheelt +/- 1000eu per maand aan AWS kosten
    * Qua onderhoud wordt het ook een stuk goedkoper, nu moet ik regelmatig 2x onderhoud plegen of 2x iets op AWS implementeren
    * Features van Publinova komen nog meer beschikbaar voor Edusources. Denk bijvoorbeeld aan auteur en project pagina's.
    * Hierarchie van instellingen organiseren/opslaan is makkelijker als het platform breedt gedragen wordt

Openstaande vragen:
	* Extraction mapping kan eruit?
	* Auteurs en projecten als middleware of geindexeerd?

Nog even een overzichtje van openstaande issues voor Publinova:
	* Alleen HAN, VHL en HKU staan op productie. Alle andere bronnen *niet*. Deze staan alleen op acceptance.
	* De organisatie structuur van Hanze opnemen ligt momenteel stil naar mijn idee.
	* SIA koppeling moet ook een beslissing over genomen worden. Hangt nu al maanden stil: https://github.com/nppo/ppp/issues/13
    * Matomo moet update krijgen naar SiteSearch

Dit zijn dingen die moeten gebeuren om Edusources en Publinova samen te voegen:
	* Configuratie moet gerefactord waarbij account_id als environment variable gebruikt moet worden
	* Alle splits die plaatsvinden (serializer) moet in settings file geregeld worden, niet met if-statements
	* Tests moeten ingeschakeld worden en test data toegevoegd/gegenereerd om de tests te laten slagen
	* Moet er al een flag op Document om materialen en resultaten streng te scheiden?
    * harvest sources moeten site_id gaan gebruiken
    * delete NPPO locales
	* Minimal education level as part of settings file

**Comment by EvaWoertman** [comment]
@martineteirlinck en @fako wat is hierin een goede volgende stap om dit te kunnen beslissen?

**Comment by fako** [comment]
The conversations around this ticket are done. A proposal has been written and shared among stakeholders. We'll create other stories to implement this change when the plan gets approved.
