### ISSUE TITLE
Update fixtures to include all approved sources

### ISSUE THREAD

**Issue by fako** [nppo/search-portal#59]

**Comment by JohnMeurs** [comment]
Conform:
https://surf.sharepoint.com/:x:/r/sites/m365-NPPOEX-team/Transitiefase/NPT-1%20Website%20en%20koppelingen/Koppelingen/Status%20koppelingen%20hogescholen_transitie.xlsx?d=w6b2497cb6a6c41c5bc73aef6f3577af9&csf=1&web=1&e=y6DG9R
